# Generated by Django 5.2.8 on 2025-12-24 03:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Посещаемость', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='groupstudent',
            options={'verbose_name': 'Ученик группы', 'verbose_name_plural': 'Ученики групп'},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='task_text',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='training_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='training_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='groupstudent',
            unique_together={('group', 'student')},
        ),
        migrations.RemoveField(
            model_name='gym',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Default Team', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='joined_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='name',
            field=models.CharField(default='Default Place', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='trainings.group'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gym',
            name='work_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='groupstudent',
            name='joined_at',
        ),
    ]
