# Generated by Django 5.2.8 on 2026-01-17 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_attendance_options_alter_homework_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='training',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='trainings.group'),
        ),
    ]
