# Generated by Django 5.2.8 on 2026-01-29 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_training_options_training_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='trainings.training'),
        ),
    ]
