# Generated by Django 5.2.8 on 2026-01-30
# Migration to change work_time to work_start and work_end fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_alter_homework_training'),
    ]

    operations = [
        # Remove old work_time field
        migrations.RemoveField(
            model_name='gym',
            name='work_time',
        ),
        # Add work_start field
        migrations.AddField(
            model_name='gym',
            name='work_start',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        # Add work_end field (optional)
        migrations.AddField(
            model_name='gym',
            name='work_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
