# Generated by Django 5.2.8
# Migration: add min_age, max_age to Group for age filtering

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_gym_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст от'),
        ),
        migrations.AddField(
            model_name='group',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст до'),
        ),
    ]
