# Generated by Django 5.2.8 on 2026-02-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_training_time_start_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['date', 'time_start'], 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
    ]
