# Generated by Django 5.2.8 on 2026-01-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_achievement_options_alter_clubteam_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubTeam',
        ),
    ]
