# Generated by Django
# Remove telegram_id from User model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patronymic_medical_insurance_remove_passport_snils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
    ]
