# Generated by Django 5.2.8 on 2025-12-24 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.BooleanField(default=True)),
                ('technique_score', models.IntegerField(blank=True, null=True)),
                ('kata_score', models.IntegerField(blank=True, null=True)),
                ('kumite_score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='journal_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_journals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_notes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заметка о прогрессе',
                'verbose_name_plural': 'Заметки о прогрессе',
            },
        ),
        migrations.CreateModel(
            name='TechniqueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=200)),
                ('mastery_level', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись техники',
                'verbose_name_plural': 'Записи техник',
            },
        ),
    ]
