# Generated by Django 5.2.8 on 2026-02-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='kata_score',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='kumite_score',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='technique_score',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='video',
        ),
    ]
