# Generated by Django 5.2.8 on 2025-12-24 03:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterModelOptions(
            name='competitioncategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='competitionregistration',
            options={'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрации'},
        ),
        migrations.AlterModelOptions(
            name='competitionresult',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterModelOptions(
            name='teamcompetitionresult',
            options={'ordering': ['place'], 'verbose_name': 'Командный результат', 'verbose_name_plural': 'Командные результаты'},
        ),
        migrations.RenameField(
            model_name='teamcompetitionresult',
            old_name='achievements',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='notes',
        ),
        migrations.AddField(
            model_name='teamcompetitionresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamcompetitionresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competitioncategory',
            name='age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitioncategory',
            name='age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitioncategory',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='competitions.competition'),
        ),
        migrations.AlterField(
            model_name='competitioncategory',
            name='weight_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitioncategory',
            name='weight_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitionregistration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitioncategory'),
        ),
        migrations.AlterField(
            model_name='teamcompetitionresult',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_results', to='competitions.competition'),
        ),
    ]
