# Generated by Django 5.2.8 on 2026-01-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_visible_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamCompetitionResult',
        ),
    ]
