# Generated by Django
# Delete CompetitionResult model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_delete_teamcompetitionresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionResult',
        ),
    ]
